#!/usr/bin/env python

from sys import argv

file = argv[1]
lines = int(argv[2]) - 1

with open(file) as f:
	linelist = list(f)

for line in linelist[:lines]:
	print line
print "======"
for line in linelist[-lines:]:
	print line
